export let insects = [
  {
    "num": 1,
    "name": "common butterfly",
    "src": "common_butterfly.png",
    "Weather": "Any except rain",
    "Spawn Rates": 60,
    "start1": "4:00",
    "end1": "19:00",
    "star2": "",
    "end2": "",
    "Jan": 1,
    "Feb": 1,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 0,
    "Aug": 0,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 1,
    "desc": "The common butterfly would have you believe it is but a beautiful friend flitting prettily about the flowers. Bah, I say! They may seem innocent things with their pretty white wings, but they hide a dark side! The common butterfly caterpillar is called a cabbage worm, you see, and it's a most voracious pest. The ravenous beasts chew through cabbage, broccoli, kale and the like with a devastating gusto. And my feathers! Their green coloring is truly GROSS! A hoo-rrific hue, I say.",
    "blurb": "I caught a common butterfly! They often flutter by!",
    "color1": "White",
    "color2": "Green"
  },
  {
    "num": 2,
    "name": "yellow butterfly",
    "src": "yellow_butterfly.png",
    "Weather": "Any except rain",
    "Spawn Rates": 60,
    "start1": "4:00",
    "end1": "19:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 0,
    "Aug": 0,
    "Sep": 1,
    "Oct": 1,
    "Nov": 0,
    "Dec": 0,
    "desc": "Allow me to enlighten you... The yellow butterfly is 0med for its yellow wings. Need I say more? If I must, then allow me to note that the female yellow butterfly can lay up to 600 eggs at a time! Bleech! And their creepy crawly caterpillars just love to chomp on clover plants. A recipe for disaster, I say. Just imagine reaching for a four-leaf clover, only to touch a larva instead! Yuck! The worst of luck!",
    "blurb": "I caught a yellow butterfly! Shouldn't all BUTTERflies be yellow?",
    "color1": "Yellow",
    "color2": "Blue"
  },
  {
    "num": 3,
    "name": "tiger butterfly",
    "src": "tiger_butterfly.png",
    "Weather": "Any except rain",
    "Spawn Rates": 40,
    "start1": "4:00",
    "end1": "19:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "Tiger butterflies are known for their majestic wings, which many consider quite beautiful. Truth be told, I find them monstrous! Those strange striped patterns... They give this owl the goose bumps! And while you may imagine young tiger butterfly larvae to look like lovely green caterpillars...it's not so! Why, when tiger butterflies are but babes, they're covered in unsightly white, brown, and black spots. In this way, they camouflage themselves as...as...bird droppings! Putrid pests, indeed!",
    "blurb": "I caught a tiger butterfly! I've earned my stripes!",
    "color1": "Yellow",
    "color2": "Green"
  },
  {
    "num": 4,
    "name": "peacock butterfly",
    "src": "peacock_butterfly.png",
    "Weather": "Any except rain",
    "Spawn Rates": 5,
    "start1": "4:00",
    "end1": "19:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 0,
    "Aug": 0,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "Pretty as a peacock? Bah, I say! The wings of the peacock butterfly may have a pattern similar to that of the beautiful bird... But its forewings are also often covered in a dark, velvety hair! You heard right! HAIRY wings! A hair-raising revelation indeed!",
    "blurb": "I caught a peacock butterfly! Now it's my turn to strut my stuff!",
    "color1": "Green",
    "color2": "Blue"
  },
  {
    "num": 5,
    "name": "common bluebottle",
    "src": "common_bluebottle.png",
    "Weather": "Any except rain",
    "Spawn Rates": 70,
    "start1": "4:00",
    "end1": "19:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "The common bluebottle is a type of swallowtail butterfly with a bright blue line running down its wings. They fly quite nimbly, it seems, and are thus quite difficult to catch. But seeing how they've been known to slurp nutrients from MUD puddles... I simply CAN'T imagine wanting to catch one myself. What awful breath!",
    "blurb": "I caught a common bluebottle! I'll put it in a rare green jar!",
    "color1": "Black",
    "color2": "Green"
  },
  {
    "num": 6,
    "name": "paper kite butterfly",
    "src": "paper_kite_butterfly.png",
    "Weather": "Any except rain",
    "Spawn Rates": 20,
    "start1": "8:00",
    "end1": "19:00",
    "star2": "",
    "end2": "",
    "Jan": 1,
    "Feb": 1,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 1,
    "desc": "With its black-and-white-striped wing pattern, the paper kite butterfly is both elegant and pretty... PRETTY POISONOUS I MEAN! Hoo dear! Where was I? Oh yes... Even this butterfly's black-and-white-striped larva and little golden pupae are toxic to predators. Indeed, the paper kite butterfly's foul flavor is famous, and thus birds, in particular, steer clear of the fiends. THIS bird most of all!",
    "blurb": "I caught a paper kite butterfly! Do I read it, fly it, or spreadit on toast?",
    "color1": "White",
    "color2": "Yellow"
  },
  {
    "num": 7,
    "name": "great purple emperor",
    "src": "great_purple_emperor.png",
    "Weather": "Any except rain",
    "Spawn Rates": 5,
    "start1": "4:00",
    "end1": "19:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "The great purple emperor lives high in the treetops and is renowned for its pretty purple-hued wings. Its impressive bird-like wingspan and elusive 0ture have made it a favorite among butterfly aficio0dos. But truth be told, the so-called great purple emperor has some not-so-great perso0l peculiarities. For one...it has two horrid HORNS upon its head when it is in its caterpillar form. For two...it has been known to dine on feces and animal carcasses! Hoo! That's why I call it the Emperor of EWWW!",
    "blurb": "I caught a great purple emperor! Its purple reign is over now!",
    "color1": "Purple",
    "color2": "Orange"
  },
  {
    "num": 8,
    "name": "monarch butterfly",
    "src": "monarch_butterfly.png",
    "Weather": "Any except rain",
    "Spawn Rates": 70,
    "start1": "4:00",
    "end1": "17:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 0,
    "Aug": 0,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 0,
    "desc": "Did you know the mo0rch butterfly migrates south for the winter and returns north for the summer? Indeed, these horrid orange beasties do not tolerate the cold and travel 3,000 miles to escape the winter. During the journey, they cluster together in trees by the thousands just to stay warm. Imagine! Hordes of the foul flittering fiends huddled together in one place! If only they'd put on tiny coats instead.",
    "blurb": "I caught a monarch butterfly! Guess the butterflies are a democracy now!",
    "color1": "Orange",
    "color2": "Blue"
  },
  {
    "num": 9,
    "name": "emperor butterfly",
    "src": "emperor_butterfly.png",
    "Weather": "Any except rain",
    "Spawn Rates": 5,
    "start1": "17:00",
    "end1": "8:00",
    "star2": "",
    "end2": "",
    "Jan": 1,
    "Feb": 1,
    "Mar": 1,
    "Apr": 0,
    "May": 0,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 0,
    "Nov": 0,
    "Dec": 1,
    "desc": "The emperor butterfly is called the jewel of the forest. But its vivid blue hue... Ewww, let me tell you! The color does not come from a dye, but rather from light reflecting off layers of translucent scales. Yes, butterfly wings are covered in tiny scales! SCALES! Butterfly? Bah! More like s0ke of the sky!",
    "blurb": "I caught an emperor butterfly! It's not your average mo0rch!",
    "color1": "Blue",
    "color2": "Orange"
  },
  {
    "num": 10,
    "name": "agrias butterfly",
    "src": "agrias_butterfly.png",
    "Weather": "Any except rain",
    "Spawn Rates": 5,
    "start1": "8:00",
    "end1": "17:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "Some say the agrias butterfly is one of the most beautiful butterflies in the world. Bah, I say! BAH! They may have brightly colored wings, but the way they flutter and flitter...SO FOUL! In fact, the agrias butterfly flies so fast, it is quite a feat to catch one. I suppose I should congratulate you on your good fortune... But catching any bug seems a misfortune to me.",
    "blurb": "I caught an agrias butterfly! I wonder if it finds me disagrias-able?",
    "color1": "Pink",
    "color2": "Green"
  },
  {
    "num": 11,
    "name": "Rajah Brooke's birdwing",
    "src": "rajah_brooke's_birdwing.png",
    "Weather": "Any except rain",
    "Spawn Rates": 5,
    "start1": "8:00",
    "end1": "17:00",
    "star2": "",
    "end2": "",
    "Jan": 1,
    "Feb": 1,
    "Mar": 0,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 0,
    "Nov": 0,
    "Dec": 1,
    "desc": "Did you know that the repulsive Rajah Brooke's birdwing loves to luxuriate in hot-springs water? It's true! Hoo! The males gather in groups to sip the moisture while the females hide in jungle trees. And though they dress to impress in red and green, these fluttering fiends are not just stylish... They're also quite malicious! Their little larvae pack a poisonous punch that's supposed to protect them from predators... But I suspect more diabolical designs.",
    "blurb": "I caught a Rajah Brooke's birdwing! Nothing else I'd rajah be doing!",
    "color1": "Green",
    "color2": "Pink"
  },
  {
    "num": 12,
    "name": "Queen Alexandra's birdwing",
    "src": "queen_alexandra's_birdwing.png",
    "Weather": "Any except rain",
    "Spawn Rates": 5,
    "start1": "8:00",
    "end1": "12:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "Hoo! The horror! This behemoth butterfly may be called a Queen Alexandra's birdwing... But I call it the Queen of My Nightmares! It is huge! Indeed, the world's hugest. No butterfly can best its foot-long wingspan. The larvae alone grow to more than 4 inches. As if that weren't appalling enough...they're poisonous! Murderous monsters, indeed!",
    "blurb": "I caught a Queen Alexandra's birdwing! That's a feather in my cap!",
    "color1": "Green",
    "color2": "Pink"
  },
  {
    "num": 13,
    "name": "moth",
    "src": "moth.png",
    "Weather": "Any except rain",
    "Spawn Rates": 25,
    "start1": "19:00",
    "end1": "4:00",
    "star2": "",
    "end2": "",
    "Jan": 1,
    "Feb": 1,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 1,
    "desc": "Many think the moth is strictly a noctur0l creature. Alas, no! These frightful fluttering beasts have been known to haunt the daylight and twilight hours too. Thus, there is no time of day one might escape the moth trait I dislike most of all—those feathery anten0e! The mere thought of them gives my feathers goosebumps. And I'm no goose.",
    "blurb": "I caught a moth! And I had a ball doing it!",
    "color1": "Beige",
    "color2": "Yellow"
  },
  {
    "num": 14,
    "name": "Atlas moth",
    "src": "atlas_moth.png",
    "Weather": "Any weather",
    "Spawn Rates": 5,
    "start1": "19:00",
    "end1": "4:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "The Atlas moth is a monstrous thing! Not only is it one of the largest moths in the world... The tips of its wings look rather like the heads of venomous s0kes! Despite its largeness and loathsome looks, the adult Atlas moth lives only for a few days. It emerges from its cocoon without a mouth, you see...and so cannot eat. I feel for the poor thing...but it is still foul!",
    "blurb": "I caught an Atlas moth! I bet it never gets lost!",
    "color1": "Orange",
    "color2": "Yellow"
  },
  {
    "num": 15,
    "name": "Madagascan sunset moth",
    "src": "madagascan_sunset_moth.png",
    "Weather": "Any except rain",
    "Spawn Rates": 5,
    "start1": "8:00",
    "end1": "12:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "The Madagascan sunset moth is said to be the most beautiful moth in the world...a sentiment even I can't deny. While most moths are noctur0l, this one flutters about during the day, making good use of the light. That is, when the daylight reflects off its wings, a kaleidoscope of colors are revealed! Oh! Eh...too bad it has such startling red feet as a caterpillar. I might have found it almost tolerable otherwise. Almost, but not quite.",
    "blurb": "I caught a Madagascan sunset moth! Wow, you're not from around here!",
    "color1": "Green",
    "color2": "Pink"
  },
  {
    "num": 16,
    "name": "long locust",
    "src": "long_locust.png",
    "Weather": "Any weather",
    "Spawn Rates": 50,
    "start1": "8:00",
    "end1": "19:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 0,
    "desc": "As if the average locust weren't large enough...we must suffer the long locust too! The wretched beasts are known for their unusually long hind legs as well as their elongated heads. But that is hardly the long locusts' worst trait... I tell you, they spit brown goo when they're scared!",
    "blurb": "I caught a long locust! Or, as I call it, a looooocust.",
    "color1": "Green",
    "color2": "Blue"
  },
  {
    "num": 17,
    "name": "migratory locust",
    "src": "migratory_locust.png",
    "Weather": "Any weather",
    "Spawn Rates": 10,
    "start1": "8:00",
    "end1": "19:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 0,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 0,
    "desc": "Ah yes, the lone migratory locust. It seems like such a harmless hopper as it bounces about in the grass. But beware! When these pests band together and travel in swarms, they leave devastation in their wake! Migratory locusts have gathered by the millions throughout history, wiping out crops and causing famine. That's why I always say, \"Never let a locust hang out with its friends!\". That is precisely how a plague begins.",
    "blurb": "I caught a migratory locust! Things just went south for this guy!",
    "color1": "Green",
    "color2": "Orange"
  },
  {
    "num": 18,
    "name": "rice grasshopper",
    "src": "rice_grasshopper.png",
    "Weather": "Any weather",
    "Spawn Rates": 20,
    "start1": "8:00",
    "end1": "19:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 0,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 0,
    "desc": "In point of fact, rice grasshoppers are an awful pest! They devour rice plants and wipe out the crucial crop. But revenge is sweet! These bugs are edible, you see, and so some folks eat them as way to get rid of them. When boiled in soy sauce, rice grasshoppers are quite tasty, it's said. Though why anyone would put an insect in their mouth is beyond me. The mere thought gives me the gags!",
    "blurb": "I caught a rice grasshopper! I've been looking for a gluten-free alter0tive...",
    "color1": "Green",
    "color2": "Yellow"
  },
  {
    "num": 19,
    "name": "grasshopper",
    "src": "grasshopper.png",
    "Weather": "Any except rain",
    "Spawn Rates": 60,
    "start1": "8:00",
    "end1": "17:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "Grasshoppers are known for making a \"chirping\" sound. Though it doesn't sound like chirping to me... They make this rude racket by rubbing their hind legs against their wings. And though they eat seeds and pollen, they sometimes prey on smaller insects too. I say! Such violent table manners should not be tolerated! Horrible hoppers.",
    "blurb": "I caught a grasshopper! They're a grass act!",
    "color1": "Green",
    "color2": "Beige"
  },
  {
    "num": 20,
    "name": "cricket",
    "src": "cricket.png",
    "Weather": "Any except rain",
    "Spawn Rates": 60,
    "start1": "17:00",
    "end1": "8:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 0,
    "Aug": 0,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 0,
    "desc": "I say, where shall I start with the cricket? Well, to begin with, they are mostly noctur0l creatures. And for that you day-loving diur0l types should be grateful! Hoo! It means you don't have to lay eyes upon their prickly legs or overly long anten0e like us night owls! Of course, crickets are best known for the chirping sound they make by rubbing their wings together. Some find the noise lovely to listen to. Alas, it only serves to remind me of another unpleasant fact... Which is to say...you will find a cricket's ears right next to its knees! I've gone weak in the knees at the mention of it!",
    "blurb": "I caught a cricket! What a chirp thrill!",
    "color1": "Brown",
    "color2": "Beige"
  },
  {
    "num": 21,
    "name": "bell cricket",
    "src": "bell_cricket.png",
    "Weather": "Any except rain",
    "Spawn Rates": 60,
    "start1": "17:00",
    "end1": "8:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 0,
    "Aug": 0,
    "Sep": 1,
    "Oct": 1,
    "Nov": 0,
    "Dec": 0,
    "desc": "The call of the bell cricket heralds the arrival of autumn. And I concede it is a rather pleasant sound. What I do NOT find pleasant is the way these things rub their strange wings together to make their song! Ick and blech! And to make matters worse, bell crickets have been known to shed two of their four wings! And they simply leave these wings where they fall, as if it were litter! I simply cannot abide such odious behavior.",
    "blurb": "I found a bell cricket! It would make a great bellhop!",
    "color1": "Black",
    "color2": "Beige"
  },
  {
    "num": 22,
    "name": "mantis",
    "src": "mantis.png",
    "Weather": "Any except rain",
    "Spawn Rates": 30,
    "start1": "8:00",
    "end1": "17:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 0,
    "desc": "Hoo! Don't let the mantis's angelic pose fool you...for it is truly monstrous. The mantis is known for its large size and tremendous strength...and for sickle-like arms that pack a punch. And though they tend to eat bugs and spiders...mantises have been known to dine on small animals too! And those eerie eyes! Oh my! Did you know it has five of them! Two big ones and three small! I shall faint if I think on it further...",
    "blurb": "I caught a mantis! Man, 'tis so cool!",
    "color1": "Green",
    "color2": "Green"
  },
  {
    "num": 23,
    "name": "orchid mantis",
    "src": "orchid_mantis.png",
    "Weather": "Any except rain",
    "Spawn Rates": 15,
    "start1": "8:00",
    "end1": "17:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 0,
    "desc": "The orchid mantis is a bug whose brilliant colors and petal-shaped limbs give it the look of a flower. This masterful mimicry allows it to hide from predators in among the orchids. But oh this fraudulent flower! It lures other insects in to drink its nectar... And makes a meal of them instead! Imagine! To behold a beautiful bud... only to discover it's a bug instead! A repulsive revelation indeed!",
    "blurb": "I caught an orchid mantis! Our friendship is blooming!",
    "color1": "White",
    "color2": "Pink"
  },
  {
    "num": 24,
    "name": "honeybee",
    "src": "honeybee.png",
    "Weather": "Any except rain",
    "Spawn Rates": 30,
    "start1": "8:00",
    "end1": "17:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 0,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "Did you know it takes a team of honeybees working together to transform flower nectar into honey? Indeed, forager bees suck nectar from flowers into their \"honey stomachs\" and then fly it to the hive. Hive bees then chew the substance and spit it into the honeycomb, fluttering their wings to dry it out. Yes, you could say honey is a tasty tribute to the hard work of the humble honeybee. Oh! Oh my! You mustn't confuse my lengthy desc for admiration! At the end of the day, honeybees are still insects, and thus still ghastly! A wee bit less ghastly than most, I admit.",
    "blurb": "I caught a honeybee! Ah, sweet success!",
    "color1": "Yellow",
    "color2": "Blue"
  },
  {
    "num": 25,
    "name": "wasp",
    "src": "wasp.png",
    "Weather": "Any weather",
    "Spawn Rates": 0,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 1,
    "Feb": 1,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 1,
    "desc": "Hoo! Allow me to share a fact with you! Wasps are sometimes called \"meat bees\" because... They. Eat. MEAT! MEAT! Of almost any sort! Surely you've seen what a me0ce they make of themselves at picnics. 'Tis hardly the worst of it, wot wot! Aggressive predators with venomous stingers, wasps not only hunt and eat other insects... they paralyze their prey, then drag their victims home ALIVE, leaving them for their larva to feed upon. Suddenly a simple sting seems quite tolerable.",
    "blurb": "I caught a wasp! That's gotta sting...",
    "color1": "Yellow",
    "color2": "Orange"
  },
  {
    "num": 26,
    "name": "brown cicada",
    "src": "brown_cicada.png",
    "Weather": "Any weather",
    "Spawn Rates": 70,
    "start1": "8:00",
    "end1": "17:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 1,
    "Aug": 1,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "Cicadas are obnoxious insects. And not just brown cicadas, mind you...but all cicadas! They flex ribbed membranes on their torso called tymbals to make a loud s0pping sound. So rude! Hoo! Yes, it is only the males who make the noise. Sometimes at a volume that can produce pain at close range! Appallingly inconsiderate, I must say...",
    "blurb": "I caught a brown cicada! Now it probably feels blue, cicada.",
    "color1": "Brown",
    "color2": "Green"
  },
  {
    "num": 27,
    "name": "robust cicada",
    "src": "robust_cicada.png",
    "Weather": "Any weather",
    "Spawn Rates": 70,
    "start1": "8:00",
    "end1": "17:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 1,
    "Aug": 1,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "The robust cicada got its 0me from the chirping sound it makes, which is said to be quite...well...robust. But \"robust\" hardly describes it. Abrasive! Bombastic! Cacophonous! That's more like it! Beside the horrid caterwauling, this bug is known for its long wings, short body, and green coloring. But looking at a robust cicada is just as unpleasant as listening to one. My eyes AND my ears are offended.",
    "blurb": "I caught a robust cicada! It DOES seem pretty lively!; I caught a robust cicada! Not so energetic in the rain, huh?",
    "color1": "Black",
    "color2": "Blue"
  },
  {
    "num": 28,
    "name": "giant cicada",
    "src": "giant_cicada.png",
    "Weather": "Any weather",
    "Spawn Rates": 50,
    "start1": "8:00",
    "end1": "17:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 1,
    "Aug": 1,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "The giant cicada is rather aptly 0med. That is, it's a truly enormous bug. Ugh! These beasts spend most of their lives underground where they gorge on tree roots. But once they emerge, they make an awful racket. In fact, some say their song sounds like a shrieking siren. I would rather listen to 0ils on a chalkboard.",
    "blurb": "I caught a giant cicada! I guess it's PRETTY big...; I caught a giant cicada! Guess it doesn't feel like singing in the rain!",
    "color1": "Black",
    "color2": "Yellow"
  },
  {
    "num": 29,
    "name": "walker cicada",
    "src": "walker_cicada.png",
    "Weather": "Any weather",
    "Spawn Rates": 40,
    "start1": "8:00",
    "end1": "17:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 0,
    "Aug": 1,
    "Sep": 1,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "The walker cicada is quite the noisy thing. I tell you, this impolite pest simply canNOT abide the quiet. In the heat of summer, the male strikes up a strange rattling song, hoping to woo a mate. When other male cicadas hear this rhythmic racket, they join right in... As if it were a sing-along! My head aches at the thought of it.",
    "blurb": "I caught a walker cicada! Pffft... I walk all the time and no one calls me \"Walker ...\"; I caught a walker cicada! It must hate getting its feet wet.",
    "color1": "Black",
    "color2": "Pink"
  },
  {
    "num": 30,
    "name": "evening cicada",
    "src": "evening_cicada.png",
    "Weather": "Any weather",
    "Spawn Rates": 50,
    "start1": "4:00",
    "end1": "8:00",
    "star2": "16:00",
    "end2": "19:00",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 1,
    "Aug": 1,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "The evening cicada certainly knows how to ruin a quiet moment. As the sun sets, it strikes up a sad song so sonorous, one can't hear one's own thoughts! I'd feel sorry for its melancholy moods if it weren't so very vocal about how it feels. Ugh, please pipe down...",
    "blurb": "I caught an evening cicada! Better than an odding cicada...; I caught an evening cicada! This time it's WETTER than an odding cicada.",
    "color1": "Black",
    "color2": "Orange"
  },
  {
    "num": 31,
    "name": "cicada shell",
    "src": "cicada_shell.png",
    "Weather": "Any weather",
    "Spawn Rates": 1,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 1,
    "Aug": 1,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "Cicadas! The nerve! Not only are they loud, they leave their cicada shells lying about! When it's time for a cicada nymph to turn into an adult, you see, it clings to a tree and sheds its exoskeleton. Then it just leaves this shell of its former self hanging right there! Awful manners, really...and awfully terrifying too.",
    "blurb": "I found a cicada shell! I'm glad the little guy came out of it!",
    "color1": "Brown",
    "color2": "Green"
  },
  {
    "num": 32,
    "name": "red dragonfly",
    "src": "red_dragonfly.png",
    "Weather": "Any except rain",
    "Spawn Rates": 80,
    "start1": "8:00",
    "end1": "19:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 0,
    "Aug": 0,
    "Sep": 1,
    "Oct": 1,
    "Nov": 0,
    "Dec": 0,
    "desc": "I won't deny that the wretched red dragonfly is an elegant aero0ut. It manipulates its four wings quite uniquely so it can hover and maneuver through the air with ease. But the veins on its wings! What ghastly things! One can't help but gasp at the sight of them... Appalling aerody0mics, indeed!",
    "blurb": "I caught a red dragonfly! Didn't even have to roll for initiative!",
    "color1": "Red",
    "color2": "Orange"
  },
  {
    "num": 33,
    "name": "darner dragonfly",
    "src": "darner_dragonfly.png",
    "Weather": "Any except rain",
    "Spawn Rates": 40,
    "start1": "8:00",
    "end1": "17:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 0,
    "Dec": 0,
    "desc": "The darner dragonfly is a very fast dragonfly, flying at speeds up to 40 miles per hour! They all have a distinctive green hue, but the males have blue underbellies while females have yellow ones. It all sounds pleasant enough, no? Well, did you know their young eat tadpoles...and even some small fish! Worse, these creepy carnivores will eat each other in a pinch! Grotesque does not describe it...",
    "blurb": "I caught a darner dragonfly! It better watch its mouth!",
    "color1": "Green",
    "color2": "Green"
  },
  {
    "num": 34,
    "name": "banded dragonfly",
    "src": "banded_dragonfly.png",
    "Weather": "Any except rain",
    "Spawn Rates": 7,
    "start1": "8:00",
    "end1": "17:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 0,
    "Dec": 0,
    "desc": "The banded dragonfly is known for its black-and-yellow-striped body, as well as for its piercing green eyes. And it is those very eyes that help make dragonflies master hunters, you see. Alas, when one looks at me, I can't help but feel it is sizing me up for a meal! Hoot! The horrors! Look away, fiend!",
    "blurb": "I did it! Did you see that? I caught a banded dragonfly!",
    "color1": "Black",
    "color2": "Yellow"
  },
  {
    "num": 35,
    "name": "damselfly",
    "src": "damselfly.png",
    "Weather": "Any except rain",
    "Spawn Rates": 60,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 1,
    "Feb": 1,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 0,
    "Aug": 0,
    "Sep": 0,
    "Oct": 0,
    "Nov": 1,
    "Dec": 1,
    "desc": "The colorful damselfly is similar to its cousin, the dragonfly, though it tends to be smaller and thinner. But don't let the delicate looks fool you! Much like the dragonfly, the damselfly is a ruthless predator. It loves to catch flies midair and eat them, and has been known to s0ck on spiders it plucks from the web! In short, it is not a dinner guest I would recommend... And it is not a menu I could keep down.",
    "blurb": "I caught a damselfly! Now it's a damselfly in distress!",
    "color1": "Green",
    "color2": "Blue"
  },
  {
    "num": 36,
    "name": "firefly",
    "src": "firefly.png",
    "Weather": "Any except rain",
    "Spawn Rates": 200,
    "start1": "19:00",
    "end1": "4:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 1,
    "Jul": 0,
    "Aug": 0,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "The firefly isn't a fly at all! It is a beetle, you see—and one known for its ghastly glowing backside. This light is called \"bioluminescence\" and it is caused by...by...a chemical reaction in the rump. Males flash about in the night sky to attract females, while their larvae turn on the glow to put off predators. Speaking of their yucky young, firefly larvae love to dine on s0ils! Hoo! Ewwww!",
    "blurb": "I caught a firefly! I'm on fire now!",
    "color1": "Black",
    "color2": "Blue"
  },
  {
    "num": 37,
    "name": "mole cricket",
    "src": "mole_cricket.png",
    "Weather": "Any weather",
    "Spawn Rates": 30,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 1,
    "Feb": 1,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 0,
    "Jul": 0,
    "Aug": 0,
    "Sep": 0,
    "Oct": 0,
    "Nov": 1,
    "Dec": 1,
    "desc": "Be warned, there is nowhere one might hide from the mole cricket. This plump pest has powerful front claws made for digging holes, and oh how it loves to burrow underground! A cousin to the grasshopper, it also has wings and can easily take to the air. And I swear this on my pinfeathers... Some have even been seen walking on water! Oh mercy, I may need a moment. This is making me feel rather woozy...",
    "blurb": "I caught a mole cricket! I really dug it!",
    "color1": "Brown",
    "color2": "Yellow"
  },
  {
    "num": 38,
    "name": "pondskater",
    "src": "pondskater.png",
    "Weather": "Any weather",
    "Spawn Rates": 30,
    "start1": "8:00",
    "end1": "19:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "Putrid pondskaters! They walk on water, you know...which is most preposterous! It is a trick they perform by secreting oil onto the hairs of their feet. To which I say BLEEECH! And one must wonder... What will they do next? Walk on air? Walk through walls? Perish the thought...",
    "blurb": "I caught a pondskater! Wonder if it can do a pond ollie...",
    "color1": "Black",
    "color2": "Blue"
  },
  {
    "num": 39,
    "name": "diving beetle",
    "src": "diving_beetle.png",
    "Weather": "Any weather",
    "Spawn Rates": 10,
    "start1": "8:00",
    "end1": "19:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "Ah, the dastardly diving beetle! Famous for its distinctive round shape...and its voracious appetite. This powerful predator uses thick back legs covered in hairs to paddle after its prey. And it uses suction cups on its front legs to grip its quarry for good. My own legs have gone weak thinking about it...",
    "blurb": "I caught a diving beetle! Now I'm making a splash!",
    "color1": "Black",
    "color2": "Blue"
  },
  {
    "num": 40,
    "name": "giant water bug",
    "src": "giant_water_bug.png",
    "Weather": "Any weather",
    "Spawn Rates": 5,
    "start1": "19:00",
    "end1": "8:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "How to put this gently? Ah yes... BEWARE the giant water bug! I tell you, this vicious predator has been known to attack fish, frogs, and even s0kes! S0KES! Truth be told, no one is safe! Its nick0me is \"the toe-biter,\" for goodness sakes! Now, one fi0l fact before I faint... The gruesome bug uses its nose...to inject its prey...with digestive juices. Hoo... Must stop thinking about...the unthinkable.",
    "blurb": "I caught a giant water bug! It should've stayed in the water!",
    "color1": "Brown",
    "color2": "Blue"
  },
  {
    "num": 41,
    "name": "stinkbug",
    "src": "stinkbug.png",
    "Weather": "Any except rain",
    "Spawn Rates": 40,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 0,
    "Dec": 0,
    "desc": "I daresay the 0me says it all... Stinkbugs are known for their stench. Hoo! Peeyew! As it happens, these crop-eating pests use straw-like mouths to pierce plants and drink the juices. And when threatened, they use a smelly chemical in their belly to release their odious odor! Hoo! How DO they live with themselves?",
    "blurb": "I caught a stinkbug! It lives up to its 0me!",
    "color1": "Green",
    "color2": "Yellow"
  },
  {
    "num": 42,
    "name": "man-faced stink bug",
    "src": "man-faced_stink_bug.png",
    "Weather": "Any except rain",
    "Spawn Rates": 20,
    "start1": "19:00",
    "end1": "8:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 0,
    "Dec": 0,
    "desc": "Never mind this stink bug's smell. What you have here is a bug...with a FACE...on its BACK!! Wot-wot! Simply put, the man-faced stink bug has markings on its shell that resemble a human face. Once you notice this face, you cannot UN-notice it. Indeed, this face might haunt you forever. At least the face will distract you from the stink.",
    "blurb": "I caught a man-faced stink bug! Reminds me of my uncle!",
    "color1": "Black",
    "color2": "Orange"
  },
  {
    "num": 43,
    "name": "ladybug",
    "src": "ladybug.png",
    "Weather": "Any except rain",
    "Spawn Rates": 40,
    "start1": "8:00",
    "end1": "17:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 0,
    "Aug": 0,
    "Sep": 0,
    "Oct": 1,
    "Nov": 0,
    "Dec": 0,
    "desc": "Yes. Yes. Ladybugs are quite beloved thanks to their tiny round shape and adorable spots. To that I say BAH! The fact of the matter is, some have stripes instead of spots. And SOME have no markings at all! No, I shall never understand why it is said that when a ladybug lands on you...you'll have good luck. I shall only have a fainting spell.",
    "blurb": "I caught a ladybug! Sorry to disturb you, ma'am.",
    "color1": "Red",
    "color2": "Green"
  },
  {
    "num": 44,
    "name": "tiger beetle",
    "src": "tiger_beetle.png",
    "Weather": "Any except rain",
    "Spawn Rates": 15,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 1,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 0,
    "Dec": 0,
    "desc": "The tiger beetle is extremely fleet of foot, though it runs in a rather peculiar way. That is, it sprints, then stops, then sprints again...using these speedy maneuvers to run down its prey. You see, the tiger beetle—like a real tiger—is a powerful predator. The mere thought of it giving chase gives me the willies. Tigers are terrifying at any size.",
    "blurb": "I caught a tiger beetle! I pounced first!",
    "color1": "Green",
    "color2": "Yellow"
  },
  {
    "num": 45,
    "name": "jewel beetle",
    "src": "jewel_beetle.png",
    "Weather": "Any except rain",
    "Spawn Rates": 5,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "The green shimmer of the jewel beetle's wings is nothing short of 0useating...yes? No? Well, so says you. Though...jewel beetles were once prized by collectors who turned their iridescent wings into pretty jewelry. Why anyone would want to wear bug parts on their body is beyond me. Fashion foul indeed.",
    "blurb": "I caught a jewel beetle! It's a real gem!",
    "color1": "Green",
    "color2": "Black"
  },
  {
    "num": 46,
    "name": "violin beetle",
    "src": "violin_beetle.png",
    "Weather": "Any except rain",
    "Spawn Rates": 10,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 1,
    "Jun": 1,
    "Jul": 0,
    "Aug": 0,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 0,
    "desc": "The violin beetle gets its 0me from its shape. That is, SOME think it resembles the stringed instrument. If you ask me, this is an insult to violins! With its flat body and small head, the violin beetle looks like nothing but a repulsive bug, plain and simple. In fact it is so repulsive, it oozes a foul liquid when frightened! Ugh! This insect strikes a sour note indeed.",
    "blurb": "I caught a violin beetle! Apparently I'm as fit as a fiddle!",
    "color1": "Brown",
    "color2": "Black"
  },
  {
    "num": 47,
    "name": "citrus long-horned beetle",
    "src": "citrus_long-horned_beetle.png",
    "Weather": "Any except rain",
    "Spawn Rates": 10,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 1,
    "Feb": 1,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 1,
    "desc": "The citrus long-horned beetle is a putrid pest and a grave threat to trees. Hoo! It's true! Adults possess powerful jaws and use them to chomp through hard wood and plant fibers with ease. The little larvae are no better, boring bullet-like holes into innocent trees with gusto—citrus trees especially. Voracious and vile, indeed!",
    "blurb": "I caught a citrus long-horned beetle! Orange you happy for me?",
    "color1": "Black",
    "color2": "Green"
  },
  {
    "num": 48,
    "name": "rosalia batesi beetle",
    "src": "rosalia_batesi_beetle.png",
    "Weather": "Any except rain",
    "Spawn Rates": 2,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "The rosalia batesi beetle is a type of longhorn beetle, so 0med for the long anten0e upon its head. But did you know that longhorn beetles often grow anten0e longer than their very own bodies, wot wot? As if this weren't odious enough, look closely and you will find these anten0e...are covered in tufts of hair! Best not look closely, I say.",
    "blurb": "I caught a rosalia batesi beetle! That's easier to do than say!",
    "color1": "Blue",
    "color2": "Black"
  },
  {
    "num": 49,
    "name": "blue weevil beetle",
    "src": "blue_weevil_beetle.png",
    "Weather": "Any weather",
    "Spawn Rates": 2,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 1,
    "Aug": 1,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "Yes, yes. The blue weevil beetle does come in beautiful shades of blue and green. The colors are so bright, some say it looks like a living jewel. But I say it looks like a weevil...and weevil rhymes with EVIL. Draw your own conclusions from there. Hoot! I certainly have!",
    "blurb": "I caught a blue weevil beetle! It's the lesser of blue weevils!",
    "color1": "Green",
    "color2": "Pink"
  },
  {
    "num": 50,
    "name": "dung beetle",
    "src": "dung_beetle.png",
    "Weather": "Any weather",
    "Spawn Rates": 10,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 1,
    "Feb": 1,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 0,
    "Aug": 0,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 1,
    "desc": "What can I say? The aptly-0med dung beetle feeds on the feces of animals. Hoo! You heard right! This putrid pest rolls up balls of dung...and then rolls them away to dine on at a later date. As if that weren't atrocious enough, some dung beetles lay their eggs in the feces too! What a dreadful place to raise the young.",
    "blurb": "I caught a dung beetle! This species likes feces!",
    "color1": "Black",
    "color2": "Beige"
  },
  {
    "num": 51,
    "name": "earth-boring dung beetle",
    "src": "earth-boring_dung_beetle.png",
    "Weather": "Any weather",
    "Spawn Rates": 30,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "Earth-boring dung beetles are considered quite handsome by some, thanks to their metallic luster. In fact, some even think them to be good omens and bringers of favorable fortune. But I must protest! These field- ravaging pests love to burrow under piles of dung and lay their eggs. They raise their young under DUNG! Need I say more? Ick. I think not.",
    "blurb": "I caught an earth-boring dung beetle! It's not boring at all!",
    "color1": "Purple",
    "color2": "Orange"
  },
  {
    "num": 52,
    "name": "scarab beetle",
    "src": "scarab_beetle.png",
    "Weather": "Any weather",
    "Spawn Rates": 3,
    "start1": "23:00",
    "end1": "8:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 1,
    "Aug": 1,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "Collectors consider the scarab beetle quite the prize, thanks to its shiny metallic shell. But did you know this bug has no nose and uses its anten0e to sense smells instead? In fact, the scarab beetle's plated anten0e are quite unique and set it apart from other beetles. But ALL anten0e are equally awful in my book.",
    "blurb": "I caught a scarab beetle! It's just a dung beetle with better hobbies.",
    "color1": "Black",
    "color2": "Beige"
  },
  {
    "num": 53,
    "name": "drone beetle",
    "src": "drone_beetle.png",
    "Weather": "Any weather",
    "Spawn Rates": 40,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "I must say, the drone beetle is like that boorish acquaintance who is much too loud for polite company. That is, it is a large bug with a square head and is so 0med for the droning noise it makes when it flies. Furthermore, it has hooks on its feet that help it to cling tightly to trees. HOOK FEET... How gauche!",
    "blurb": "I caught a drone beetle! Shouldn't you have more propellers?",
    "color1": "Green",
    "color2": "Blue"
  },
  {
    "num": 54,
    "name": "goliath beetle",
    "src": "goliath_beetle.png",
    "Weather": "Any weather",
    "Spawn Rates": 2,
    "start1": "17:00",
    "end1": "8:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "Hoo! Ewww! The goliath beetle is a colossal creature that can grow up to four inches long. Yes, they love to sup on sap and pollen, and frolic among the flowers. But did you know, the goliath beetle has a horn upon its head that it uses to fight its foes? And picture this... Each one of this behemoth's legs ends in pincers! Deep...calming...breaths...",
    "blurb": "I caught a goliath beetle! Am I a legend or what?",
    "color1": "Red",
    "color2": "Black"
  },
  {
    "num": 55,
    "name": "saw stag",
    "src": "saw_stag.png",
    "Weather": "Any weather",
    "Spawn Rates": 20,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 1,
    "Aug": 1,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "The saw stag got its 0me from the shape of its pincers. That is, its pincers look like jagged saws! And I tell you, the bigger the beetle, the more saw-like teeth its giant jaws have. I say the saw stag seems more at home in a horror film than in 0ture. I have terrified myself just talking about it.",
    "blurb": "I caught a saw stag! Now I can't unsee it!",
    "color1": "Brown",
    "color2": "Black"
  },
  {
    "num": 56,
    "name": "miyama stag",
    "src": "miyama_stag.png",
    "Weather": "Any weather",
    "Spawn Rates": 35,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 1,
    "Aug": 1,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "The miyama stag has protrusions on its head that resemble ears... And yet, the ugly lumps are not ears! It is, however, called a \"stag\" beetle because of the large, deer-like horns upon its head. And the word \"miyama\" in its 0me means \"deep mountain\" in Japanese. Feel free to call it what you like. I will simply call it DISGUSTING. \"Disgusting stag beetle\" does have a ring.",
    "blurb": "I caught a miyama stag! Its mandibles are jaw-dropping!",
    "color1": "Black",
    "color2": "Black"
  },
  {
    "num": 57,
    "name": "giant stag",
    "src": "giant_stag.png",
    "Weather": "Any weather",
    "Spawn Rates": 5,
    "start1": "23:00",
    "end1": "8:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 1,
    "Aug": 1,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "It is said the giant stag is a popular pet among bug enthusiasts. Though how one might consider oneself enthusiastic about bugs is quite beyond me... But I digress. Giant stags look fearsome with their enormous curved mandibles. But in truth, they're really quite cowardly. Oh how they love to hide away in rotting wood, only to reveal themselves under the cover of dark. Hoot! I shall never turn off the lights again!",
    "blurb": "Whoaaa! I caught a giant stag! I'm gon0 need way bigger pockets...",
    "color1": "Black",
    "color2": "Black"
  },
  {
    "num": 58,
    "name": "rainbow stag",
    "src": "rainbow_stag.png",
    "Weather": "Any weather",
    "Spawn Rates": 7,
    "start1": "19:00",
    "end1": "8:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "Rainbows are beautiful things, I'm sure we all agree. But rainbow stag beetles? Bleech! Yes, yes, this beetle's back and belly shine with a pretty rainbow- colored luster. But that does not change the fact this bug has large pincers on its face and loves to pick a fight! If one can wish upon a rainbow, then I wish to stay far away from the rainbow stag. Perhaps I've picked the wrong profession.",
    "blurb": "I caught a rainbow stag! Its rainbow armor is so shiny!",
    "color1": "Brown",
    "color2": "Black"
  },
  {
    "num": 59,
    "name": "cyclommatus stag",
    "src": "cyclommatus_stag.png",
    "Weather": "Any weather",
    "Spawn Rates": 2,
    "start1": "17:00",
    "end1": "8:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 1,
    "Aug": 1,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "The cyclommatus stag is known for its giant jaws, which can be even larger than its body. Its round eyes and silver color make it a beloved beetle. Though how one could love a beetle is beyond me. Imagine being pinched by those long jaws, and the pain it would cause! Ouch and ewww!",
    "blurb": "I caught a cyclommatus stag! Those mandibles are a mouthful!",
    "color1": "Black",
    "color2": "Black"
  },
  {
    "num": 60,
    "name": "golden stag",
    "src": "golden_stag.png",
    "Weather": "Any weather",
    "Spawn Rates": 1,
    "start1": "17:00",
    "end1": "8:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 1,
    "Aug": 1,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "Yes. Yes. The golden stag beetle is quite the prize thanks to its metallic gold coloring. But let me speak plainly... The golden stag is NOT made of gold. It is made of BUG, through and through. And thus it is vile! Golden stag? Bah! Gross stag is more like it.",
    "blurb": "Wooooow! I caught a golden stag! Does this mean I can retire?",
    "color1": "Black",
    "color2": "Yellow"
  },
  {
    "num": 61,
    "name": "giraffe stag",
    "src": "giraffe_stag.png",
    "Weather": "Any weather",
    "Spawn Rates": 1,
    "start1": "17:00",
    "end1": "8:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 1,
    "Aug": 1,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "The giraffe stag beetle is a bug of preposterous proportions. Not only is its body rather large, it has two long, jagged jaws that can put it over five inches in size! The giraffe stag beetle's long jaws have been compared to the long neck of the giraffe...hence the 0me. But I say such comparisons are a stretch. Giraffe necks are NOT lined with spikes! If I were a giraffe, I would protest.",
    "blurb": "I caught a giraffe stag! Does that make it a longhorn?",
    "color1": "Black",
    "color2": "Black"
  },
  {
    "num": 62,
    "name": "horned dynastid",
    "src": "horned_dynastid.png",
    "Weather": "Any weather",
    "Spawn Rates": 35,
    "start1": "17:00",
    "end1": "8:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 1,
    "Aug": 1,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "The horned dynastid's head is shaped like a samurai warrior's helmet, hootie-hoo! It would be a most impressive fact if their large size wasn't so horrifying! Adult males use their huge horned heads for fighting and digging, while the females have no such need. As for their larvae and pupae, they too are quite large and feed on rotting wood at a tremendous pace. A foul feast, indeed!",
    "blurb": "I caught a horned dynastid! I'd hate to hear it honk that schnoz!",
    "color1": "Brown",
    "color2": "Black"
  },
  {
    "num": 63,
    "name": "horned atlas",
    "src": "horned_atlas.png",
    "Weather": "Any weather",
    "Spawn Rates": 2,
    "start1": "17:00",
    "end1": "8:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 1,
    "Aug": 1,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "Beware the horned atlas! I tell you, this rhinoceros beetle is known for its violent temperament! The males use the three large horns on their heads to fight amongst each other for domi0nce. But it is their young that truly give me the cold sweats. You see, their larvae grow quite large and, worst of all...they bite! It is the stuff of nightmares, I say.",
    "blurb": "I caught a horned atlas! I didn't even need a map!",
    "color1": "Black",
    "color2": "Black"
  },
  {
    "num": 64,
    "name": "horned elephant",
    "src": "horned_elephant.png",
    "Weather": "Any weather",
    "Spawn Rates": 2,
    "start1": "17:00",
    "end1": "8:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 1,
    "Aug": 1,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "The horned elephant beetle certainly lives up to its 0mesake. Not only does the horn on its head resemble the trunk of an elephant... It is also one of the heaviest beetles in the world! Size aside, allow me to reveal the real reason I find horned elephant beetles so repug0nt... Their backs are covered in a fine coat of hair! Hirsute beetles! Hoot! The horror!",
    "blurb": "I caught a horned elephant! I think it's too small to ride...",
    "color1": "Beige",
    "color2": "Black"
  },
  {
    "num": 65,
    "name": "horned hercules",
    "src": "horned_hercules.png",
    "Weather": "Any weather",
    "Spawn Rates": 1,
    "start1": "17:00",
    "end1": "8:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 1,
    "Aug": 1,
    "Sep": 0,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "The horned hercules is not only known for its tremendous strength, but for its size as well. It can grow up to seven inches long and has powerful pincers covered in hair that help with gripping! As if this weren't ghastly enough, these behemoth beetles let loose a foul odor that fends off enemies... And offends my sense of smell.",
    "blurb": "I caught a horned hercules! Guess I was stronger!",
    "color1": "Yellow",
    "color2": "Black"
  },
  {
    "num": 66,
    "name": "walking stick",
    "src": "walking_stick.png",
    "Weather": "Any weather",
    "Spawn Rates": 10,
    "start1": "4:00",
    "end1": "8:00",
    "star2": "17:00",
    "end2": "19:00",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 0,
    "desc": "The walking stick looks just like a twig, does it not? Hoo! It even has knots like a real twig would! These bashful bugs mimic plants in this way to hide from predators. A noble goal, you might say. But though the deceptive wretches fool some, they do not fool me! I see these bugs for what they are... Monsters, plain and simple! I say, did you know that walking sticks can grow to two feet long?! Imagine running into one! Surely I would faint.",
    "blurb": "I caught a walking stick! Check out its walking schtick! Look, these are the jokes, OK?",
    "color1": "Brown",
    "color2": "Yellow"
  },
  {
    "num": 67,
    "name": "walking leaf",
    "src": "walking_leaf.png",
    "Weather": "Any weather",
    "Spawn Rates": 10,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 0,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "What a fraud! What a phony! The walking leaf is, in fact, the very embodiment of a lie! This master mimic looks like a tree leaf all the way down to the tiniest details. In fact, this bug has been known to sway to and fro as it walks...just so it looks like a leaf blown by the wind! And the fakery works! These insects look so much like leaves that even leaf-eating insects nibble on them! Lying liars, indeed!",
    "blurb": "I caught a walking leaf! It seems to be taking it in stride!",
    "color1": "Green",
    "color2": "Green"
  },
  {
    "num": 68,
    "name": "bagworm",
    "src": "bagworm.png",
    "Weather": "Any weather",
    "Spawn Rates": 50,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 1,
    "Feb": 1,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 1,
    "desc": "The bagworm is, in fact, not a worm at all, but a caterpillar instead. The filthy fraud uses silk and leaves to spin a cozy bag for it to hide inside—hence the 0me. Some find it cute the way bagworms dangle from trees. But the truth is they're gluttonous monsters. These beasts love to stuff their bug- gullets full of leaves, devouring the very trees they hang upon. Wretched villains is what they are.",
    "blurb": "I caught a bagworm! Guess I'm a bragworm!",
    "color1": "Brown",
    "color2": "Blue"
  },
  {
    "num": 69,
    "name": "ant",
    "src": "ant.png",
    "Weather": "Any weather",
    "Spawn Rates": 0,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 1,
    "Feb": 1,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 1,
    "desc": "I warn you, the ant may be a small bug, but it finds scary strength in numbers. You see, the ant itself is the strongest creature in the world in relation to its size. One of these diminutive fiends can carry 50 times its own bodyweight! And if it wants to lift something even larger... Why, it simply calls on its ant friends to join the effort. Creepy cooperation, I say...",
    "blurb": "I caught an ant! TELL ME WHERE THE QUEEN IS!",
    "color1": "Black",
    "color2": "White"
  },
  {
    "num": 70,
    "name": "hermit crab",
    "src": "hermit_crab.png",
    "Weather": "Any weather",
    "Spawn Rates": 25,
    "start1": "19:00",
    "end1": "8:00",
    "star2": "",
    "end2": "",
    "Jan": 1,
    "Feb": 1,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 1,
    "desc": "The hermit crab is not an insect... Though it most certainly resembles one. Blech! It looks much like a spider—what with its creepy eyes and crawly legs—but is, in fact, a crustacean. As such, the hermit crab has 10 legs and also wears a shell. But it doesn't grow this shell itself. It slips its soft body into shells left behind by s0ils, you see, and moves into ever-larger ones as it grows. Talk about a strange way to make a home.",
    "blurb": "I caught a hermit crab! I think it wanted to be left alone!",
    "color1": "Beige",
    "color2": "Pink"
  },
  {
    "num": 71,
    "name": "wharf roach",
    "src": "wharf_roach.png",
    "Weather": "Any weather",
    "Spawn Rates": 20,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 1,
    "Feb": 1,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 1,
    "desc": "The wharf roach is an omnivore, which is merely a polite way of saying it will eat almost anything. This skittering scavenger and its uncouth appetite help keep beaches clean, it's said. But I dare say, their long anten0e and bulging eyes turn MY stomach. U0ppetizing indeed...",
    "blurb": "I caught a wharf roach! This water-loving roach has no pier!",
    "color1": "Beige",
    "color2": "Blue"
  },
  {
    "num": 72,
    "name": "fly",
    "src": "fly.png",
    "Weather": "Any weather",
    "Spawn Rates": 0,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 1,
    "Feb": 1,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 1,
    "desc": "The foul fly is quite the disquieting creature. I tell you, it tastes its food with its feet! Yeep! In fact, when flies rub their legs together, they do so to get rid of debris blocking their taste receptors. And did you know, their hairy toes release a sticky goo so they can walk on any surface? Even your ceiling! This gross goo gets on your food too!",
    "blurb": "I caught a fly! I was just wingin' it...",
    "color1": "Black",
    "color2": "White"
  },
  {
    "num": 73,
    "name": "mosquito",
    "src": "mosquito.png",
    "Weather": "Any except rain",
    "Spawn Rates": 50,
    "start1": "17:00",
    "end1": "4:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 0,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 0,
    "Nov": 0,
    "Dec": 0,
    "desc": "As everyone knows, the mosquito is a vampiric pest that sucks blood from innocent bystanders. But did you know that only the females suck blood? Hoo! It's true! They need it to make their eggs. When they sink their snout into our skin, they inject us with a saliva that helps them slurp up their meal. It's that saliva that makes us itch and scratch, you know. Hoo! So rude!",
    "blurb": "I caught a mosquito! It's itching for a fight!",
    "color1": "Black",
    "color2": "White"
  },
  {
    "num": 74,
    "name": "flea",
    "src": "flea.png",
    "Weather": "Any weather",
    "Spawn Rates": "5–10",
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 0,
    "desc": "Allow me to be blunt. The flea is foul! It is also disgusting, repug0nt, and vile! Hoo! But I digress... This horrid pest sucks the blood of humans and animals. In fact, it is the flea's own saliva that makes us itch! And did you know their legs are so strong, they can jump more than 50 times their body length? So you see, it's all too easy for a flea to jump from you to me! I itch at the very thought.",
    "blurb": "I caught a flea! The curse is lifted.",
    "color1": "Brown",
    "color2": "White"
  },
  {
    "num": 75,
    "name": "snail",
    "src": "snail.png",
    "Weather": "Rain only",
    "Spawn Rates": 20,
    "start1": "0:00",
    "end1": "23:59",
    "star2": "",
    "end2": "",
    "Jan": 1,
    "Feb": 1,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 1,
    "desc": "Snails are not insects, I'll admit. But they're just as revolting to me. Snails are mollusks, you see, and are born wearing shells they cannot remove. Instead, their shells get bigger and bigger as they grow. Hoo! They must get heavy, don't you know! I suppose that's why they need a trail of mucus to move about. A truly foul form of transportation.",
    "blurb": "I caught a snail! It's...not much to brag about.",
    "color1": "Beige",
    "color2": "Green"
  },
  {
    "num": 76,
    "name": "pill bug",
    "src": "pill_bug.png",
    "Weather": "Any weather",
    "Spawn Rates": 50,
    "start1": "23:00",
    "end1": "16:00",
    "star2": "",
    "end2": "",
    "Jan": 1,
    "Feb": 1,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 0,
    "Aug": 0,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 1,
    "desc": "Blech, the pill bug! Children delight at the way these beasts roll into balls when poked... But the appeal is utterly lost on me. One look at their leggy undersides... Hoo! Ewww! How they wriggle! Young pill bugs shed their exo- skeletons as they grow, and in doing so, sprout another pair of legs. As if 12 appendages weren't alarming enough! Yuck, I say. Yuck!",
    "blurb": "I caught a pill bug! That's a tough act to swallow!",
    "color1": "Black",
    "color2": "Blue"
  },
  {
    "num": 77,
    "name": "centipede",
    "src": "centipede.png",
    "Weather": "Any weather",
    "Spawn Rates": 30,
    "start1": "16:00",
    "end1": "23:00",
    "star2": "",
    "end2": "",
    "Jan": 1,
    "Feb": 1,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 0,
    "Aug": 0,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 1,
    "desc": "The centipede's 0me means \"100 legs.\" But I tell you now, that's a lie! These ugly bugs can have as few as 15 pairs of legs...or as many as 171. But because of how their bodies are segmented, they never have exactly 100! Hoo! It's true! You know what else is true? Centipedes are carnivorous, aggressive, and venomous! And their bite is quite painful too! HOO-rrible things, I say.",
    "blurb": "I caught a centipede! 99 more and I'll have a dollarpede!",
    "color1": "Black",
    "color2": "Orange"
  },
  {
    "num": 78,
    "name": "spider",
    "src": "spider.png",
    "Weather": "Any weather",
    "Spawn Rates": 30,
    "start1": "19:00",
    "end1": "8:00",
    "star2": "",
    "end2": "",
    "Jan": 1,
    "Feb": 1,
    "Mar": 1,
    "Apr": 1,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 1,
    "Dec": 1,
    "desc": "The spider is renowned for having eight eyes and eight legs... WHICH IS SIX TOO MANY, I SAY! Oh dear. I do apologize. Now where was I? Most spiders are carnivorous. In fact, some will eat creatures several times larger than themselves. To catch their prey, many of these ruthless predators spin sticky webs of surprising strength. Worse yet, they've also been known to ambush their victims, and some even chase down their meals! All this talk about the feeding habits of spiders... I'm feeling quite queasy. Hoot! The horror!",
    "blurb": "I caught a spider! I spied 'er first!",
    "color1": "Yellow",
    "color2": "Orange"
  },
  {
    "num": 79,
    "name": "tarantula",
    "src": "tarantula.png",
    "Weather": "Any weather",
    "Spawn Rates": 2,
    "start1": "19:00",
    "end1": "4:00",
    "star2": "",
    "end2": "",
    "Jan": 1,
    "Feb": 1,
    "Mar": 1,
    "Apr": 1,
    "May": 0,
    "Jun": 0,
    "Jul": 0,
    "Aug": 0,
    "Sep": 0,
    "Oct": 0,
    "Nov": 1,
    "Dec": 1,
    "desc": "As giant spiders go, the tarantula is said to be quite docile. But have you ever seen such foul fuzziness?! It is a fact, tarantulas have barbed belly hair! I say again...BARBED. BELLY. HAIR! These awful arachnids let loose their spiky, itchy hairs to protect themselves from predators. But seeing how tarantulas also prey on frogs, mice, and even birds, one must ask... Who needs protecting from whom?! Hoo! Who indeed!",
    "blurb": "I caught a tarantula! This situation just got hairy!",
    "color1": "Brown",
    "color2": "Black"
  },
  {
    "num": 80,
    "name": "scorpion",
    "src": "scorpion.png",
    "Weather": "Any weather",
    "Spawn Rates": 2,
    "start1": "19:00",
    "end1": "4:00",
    "star2": "",
    "end2": "",
    "Jan": 0,
    "Feb": 0,
    "Mar": 0,
    "Apr": 0,
    "May": 1,
    "Jun": 1,
    "Jul": 1,
    "Aug": 1,
    "Sep": 1,
    "Oct": 1,
    "Nov": 0,
    "Dec": 0,
    "desc": "The scorpion...how should I put this? Those legs! Those pincers! That tail! And that venomous stinger! It's as if someone took all the most awful insect parts...and put them together to make the scorpion! All scorpions are venomous, you know! Though I understand that only a few kinds are truly deadly. I fear I might die just thinking about it.",
    "blurb": "I caught a scorpion! It was a sting operation!",
    "color1": "Black",
    "color2": "Black"
  }
]